sudo: required
services:
        - docker
before_install:
        
        - docker build -t manikanta513/client -f ./client/Dockerfile.dev ./client
         


script:
        - docker run manikanta513/client npm test -- --coverage


after_success:
        - docker build -t manikanta513/multi-client  ./client/
        - docker build -t manikanta513/multi-nginx  ./nginx
        - docker build -t manikanta513/multi-server  ./server
        - docker build -t manikanta513/multi-worker  ./worker

# log in credentials of docker_hub
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push manikanta513/multi-client
        - docker push manikanta513/multi-nginx
        - docker push manikanta513/multi-server
        - docker push manikanta513/multi-worker

deploy:
        provider: Elasticbeanstack
        region: ap-south-1
        app: docker-project
        env: DockerProject-env
        bucket_name: elasticbeanstalk-ap-south-1-457180139478
        bucket_path: docker-multi
        on:
                branch: master
                access_key_id: $AWS_ACCESS_KEY
                secret_access_key:
                        secure: $AWS_SECRET_KEY
